	FROM nginx:latest

	WORKDIR /app
	RUN apt-get update && \
	    apt-get install vim -y
	COPY html /usr/share/nginx/html
	ENTRYPOINT ["/docker-entrypoint.sh"]
	EXPOSE 80
	STOPSIGNAL SIGTERM
	CMD ["nginx", "-g", "daemon off;"]
