version: '3'

services:

 laravel:
  image: agmoliveira/laravel:prod
   container_name: laravel
   networks:
   - laranet
 nginx:
 image: agmoliveira/nginx:prod
   container_name: nginx
     networks:
     - laranet
     ports:
      - "8080:80"
  networks:
  laranet
   driver: bridge
