version: '3'

services: 

  laravel:
    build:
     context: ./Laravel
     dockerfile: Dockerfile_prod
    image: agmoliveira/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build:
     context: ./nginx
     dockerfile: Dockerfile_nginx_prd
    image: agmoliveira/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge
